version = 1

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"